#  ______ _____   ______ __          __       _____   _____
#  |___  /|  __ \ |  ____|\ \        / //\    |  __ \ |  __ \
#  / / | |__) || |__    \ \  /\  / //  \   | |__) || |  | |
#  / /  |  _  / |  __|    \ \/  \/ // /\ \  |  _  / | |  | |
#  / /__ | | \ \ | |____    \  /\  // ____ \ | | \ \ | |__| |
#  /_____||_|  \_\|______|    \/  \//_/    \_\|_|  \_\|_____/
# Разработчик: Web/Java  |  Связаться: @zzrtk в Telegram
# Конфиг

utils:
 console-messages-plugin: true

bossbar:
  enable: false
  color: YELLOW
  title: '&fИгрок &6%player&f получил &6&l%reward&f! '

messages:
  error: '§7(&6&lZR&7)§7 &fИспользуйте: /reward <id>'
  unkownreward: '§7(&6&lZR&7)§7 &fТакой награды не существует!'
  little_play_time: '§7(&6&lZR&7)§7 &fВам не хватает: &6&l%time &fсекунд'
  re-receipt: '§7(&6&lZR&7)§7 &fВы уже получали такую награду!'

